spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3308/swbackend?useUnicode=true&characterEncoding=utf8&connectionCollation=utf8mb4_unicode_ci&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: swbackend
    password: swbackend

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: 'YmFlazNlMGstbWFwLXByb2plY3QtaXMtdmVyeS1mdW4tYW5kLXNlY3JldC1rZXktMjAyNSE='

logging:
  level:
    org.springframework.security: DEBUG